name: Deploy en EC2

on:
  push:
    branches:
      - main

jobs:
  pull-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Send SSM command to EC2 to run git pull
        run: |
          aws ssm send-command \
            --document-name "AWS-RunPowerShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --comment "Running git pull on Windows EC2" \
            --parameters 'commands=[
              "cd C:\\Neider\\Sant.top\\Portafolio",
              "git remote set-url origin https://$MY_GITHUB_TOKEN@github.com/sasugo1337/Portafolio.git",
              "C:\\\"Program Files\"\\Git\\bin\\git.exe pull",
              "C:\\\"Program Files\"\\Git\\bin\\git.exe submodule update --init --recursive",
              "C:\\\"Program Files\"\\Git\\bin\\git.exe submodule update --recursive --remote",
            ]' \
            --region us-east-2
